blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    # Просмотр деталей блога
    # cache_page(60) - кэширует результаты выполнения представления на 60 секунд
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blogs_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('mailings/', include('mailing.urls', namespace='mailing')),
    path('mailing_logs/', include('mailing_logs.urls', namespace='mailing_log')),
    path('recipients/', include('recipient.urls', namespace='recipient')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # Список рассылок
    path('', MailingListView.as_view(), name='mailings'),

    # Детали рассылки
    path('<int:pk>/', MailingDetailView.as_view(), name='mailings_detail'),

    # Создание новой рассылки
    path('create/', MailingCreateView.as_view(), name='mailings_create'),

    # Обновление рассылки
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailings_update'),

    # Удаление рассылки
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailings_delete'),

    # Изменение статуса рассылки
    path('change_status/<int:pk>/', change_mailing_status, name='change_status'),
]

main_page/urls.py
from django.urls import path

from main_page.apps import MainPageConfig
from main_page.views import main_page

app_name = MainPageConfig.name

urlpatterns = [
    path('', main_page, name='main_page'),
]

recipient/urls.py
from django.urls import path
from recipient.apps import RecipientConfig
from recipient.views import *

# Получаем имя приложения "recipient" из его конфигурации
app_name = RecipientConfig.name

urlpatterns = [
    # Маршрут для отображения списка получателей
    path('', RecipientListView.as_view(), name='recipients'),

    # Маршрут для отображения деталей конкретного получателя
    path('<int:pk>/', RecipientDetailView.as_view(), name='recipients_detail'),

    # Маршрут для создания нового получателя
    path('create/', RecipientCreateView.as_view(), name='recipients_create'),

    # Маршрут для редактирования существующего получателя
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='recipients_update'),

    # Маршрут для удаления существующего получателя
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='recipients_delete'),
]

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import *

app_name = UsersConfig.name

urlpatterns = [
    path('', UserLoginView.as_view(), name='login'),  # Страница входа пользователя.
    path('logout/', UserLogoutView.as_view(), name='logout'),  # Выход пользователя из системы.
    path('register/', UserRegisterView.as_view(), name='register'),  # Регистрация нового пользователя.
    path('profile/', UserUpdateView.as_view(), name='profile'),  # Просмотр и обновление профиля пользователя.
    path('verify/', verify, name='verify'),  # Подтверждение email адреса пользователя после регистрации.
    path('reg_confirmation/', reg_confirmation, name='reg_confirmation'),  # Страница подтверждения успешной регистрации пользователя.
    path('reset_password/', reset_password, name='reset_password'),  # Сброс пароля пользователя.
    path('new_password/', new_password, name='new_password'),  # Создание нового пароля после сброса.
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render

from mailing.models import Mailing
from main_page.services import get_blogs_cache
from recipient.models import Recipient


def main_page(request):
    """
    Отображает главную страницу.
    Args:
        request (HttpRequest): Запрос от пользователя.
    Returns:
        HttpResponse: Ответ, содержащий главную страницу.
    """
    blogs = get_blogs_cache()

    if request.user.is_authenticated:
        # Если пользователь аутентифицирован, получаем его рассылки и получателей
        mailings = Mailing.objects.filter(sender=request.user)
        active_mailings = len(Mailing.objects.filter(status=Mailing.STATUS_STARTED, sender=request.user))
        count_mailings = len(mailings)
        recipients_count = len(Recipient.objects.filter(sender=request.user))

        context = {
            'mailings': mailings,
            'active_mailings': active_mailings,
            'count_mailings': count_mailings,
            'blogs': blogs,
            'recipients_count': recipients_count,
            'title': 'Главная страница'
        }

    else:
        # Если пользователь не аутентифицирован, показываем только блоги
        context = {
            'blogs': blogs,
            'title': 'Главная страница'
        }

    return render(request, 'main_page/main_page.html', context=context)

templates/main_page/includes/inc_footer.html
<div class="container">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <p class="col-md-4 mb-0 text-body-secondary">© 2023 Lisnevskiy</p>

        <a href="{% url 'main_page:main_page' %}"
           class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" fill="currentColor" class="bi bi-mailbox" viewBox="0 0 16 16">
                <path d="M4 4a3 3 0 0 0-3 3v6h6V7a3 3 0 0 0-3-3zm0-1h8a4 4 0 0 1 4 4v6a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a4 4 0 0 1 4-4zm2.646 1A3.99 3.99 0 0 1 8 7v6h7V7a3 3 0 0 0-3-3H6.646z"/>
                <path d="M11.793 8.5H9v-1h5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.354-.146l-.853-.854zM5 7c0 .552-.448 0-1 0s-1 .552-1 0a1 1 0 0 1 2 0z"/>
            </svg>
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="{% url 'main_page:main_page' %}" class="nav-link px-2 text-body-secondary">Главная</a></li>
            <li class="nav-item"><a href="{% url 'mailing:mailings' %}" class="nav-link px-2 text-body-secondary">Рассылки</a></li>
            <li class="nav-item"><a href="{% url 'recipient:recipients' %}" class="nav-link px-2 text-body-secondary">Получатели</a></li>
        </ul>
    </footer>
</div>

templates/main_page/includes/inc_main_menu.html
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <div class="col-md-3 mb-2 mb-md-0">
            <a href="{% url 'main_page:main_page' %}" class="d-inline-flex link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" fill="currentColor" class="bi bi-mailbox" viewBox="0 0 16 16">
                    <path d="M4 4a3 3 0 0 0-3 3v6h6V7a3 3 0 0 0-3-3zm0-1h8a4 4 0 0 1 4 4v6a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V7a4 4 0 0 1 4-4zm2.646 1A3.99 3.99 0 0 1 8 7v6h7V7a3 3 0 0 0-3-3H6.646z"/>
                    <path d="M11.793 8.5H9v-1h5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.354-.146l-.853-.854zM5 7c0 .552-.448 0-1 0s-1 .552-1 0a1 1 0 0 1 2 0z"/>
                </svg>
            </a>
        </div>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'main_page:main_page' %}" class="nav-link px-2 link-secondary">Главная</a></li>
            <li><a href="{% url 'mailing:mailings' %}" class="nav-link px-2">Рассылки</a></li>
            <li><a href="{% url 'recipient:recipients' %}" class="nav-link px-2">Получатели</a></li>
        </ul>

        <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="p-2 btn btn-outline-danger me-2">Выйти</a>
            <a href="{% url 'users:profile' %}" class="p-2 btn btn-outline-success me-2">Профиль</a>
            {% else %}
            <a href="{% url 'users:login' %}" class="p-2 btn btn-outline-primary me-2">Войти</a>
            <a href="{% url 'users:register' %}" class="p-2 btn btn-primary me-2">Регистрация</a>
            {% endif %}
        <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
        </svg>
        </div>
    </header>
</div>