blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    # Просмотр деталей блога
    # cache_page(60) - кэширует результаты выполнения представления на 60 секунд
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blogs_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('mailings/', include('mailing.urls', namespace='mailing')),
    path('mailing_logs/', include('mailing_logs.urls', namespace='mailing_log')),
    path('recipients/', include('recipient.urls', namespace='recipient')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # Список рассылок
    path('', MailingListView.as_view(), name='mailings'),

    # Детали рассылки
    path('<int:pk>/', MailingDetailView.as_view(), name='mailings_detail'),

    # Создание новой рассылки
    path('create/', MailingCreateView.as_view(), name='mailings_create'),

    # Обновление рассылки
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailings_update'),

    # Удаление рассылки
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailings_delete'),

    # Изменение статуса рассылки
    path('change_status/<int:pk>/', change_mailing_status, name='change_status'),
]

main_page/urls.py
from django.urls import path

from main_page.apps import MainPageConfig
from main_page.views import main_page

app_name = MainPageConfig.name

urlpatterns = [
    path('', main_page, name='main_page'),
]

recipient/urls.py
from django.urls import path
from recipient.apps import RecipientConfig
from recipient.views import *

# Получаем имя приложения "recipient" из его конфигурации
app_name = RecipientConfig.name

urlpatterns = [
    # Маршрут для отображения списка получателей
    path('', RecipientListView.as_view(), name='recipients'),

    # Маршрут для отображения деталей конкретного получателя
    path('<int:pk>/', RecipientDetailView.as_view(), name='recipients_detail'),

    # Маршрут для создания нового получателя
    path('create/', RecipientCreateView.as_view(), name='recipients_create'),

    # Маршрут для редактирования существующего получателя
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='recipients_update'),

    # Маршрут для удаления существующего получателя
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='recipients_delete'),
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
from django.shortcuts import render

from mailing.models import Mailing
from main_page.services import get_blogs_cache
from recipient.models import Recipient


def main_page(request):
    """
    Отображает главную страницу.
    Args:
        request (HttpRequest): Запрос от пользователя.
    Returns:
        HttpResponse: Ответ, содержащий главную страницу.
    """
    blogs = get_blogs_cache()

    if request.user.is_authenticated:
        # Если пользователь аутентифицирован, получаем его рассылки и получателей
        mailings = Mailing.objects.filter(sender=request.user)
        active_mailings = len(Mailing.objects.filter(status=Mailing.STATUS_STARTED, sender=request.user))
        count_mailings = len(mailings)
        recipients_count = len(Recipient.objects.filter(sender=request.user))

        context = {
            'mailings': mailings,
            'active_mailings': active_mailings,
            'count_mailings': count_mailings,
            'blogs': blogs,
            'recipients_count': recipients_count,
            'title': 'Главная страница'
        }

    else:
        # Если пользователь не аутентифицирован, показываем только блоги
        context = {
            'blogs': blogs,
            'title': 'Главная страница'
        }

    return render(request, 'main_page/main_page.html', context=context)

templates/main_page/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'main_page/includes/inc_main_menu.html' %}
{% block content %}
{% endblock %}
{% include 'main_page/includes/inc_footer.html' %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/main_page/main_page.html
{% extends 'main_page/base.html' %}

{% block content %}


<div class="container">
    <h1 class="display-5 text-center">Сервис управления рассылками</h1>
    <p></p>
    <div class="row">
        <div class="col-2"></div>
        <a class="p-2 btn btn-outline-primary col-3" href="{% url 'recipient:recipients_create' %}">Добавьте получателя</a>
        <div class="col-2"></div>
        <a class="p-2 btn btn-outline-primary col-3" href="{% url 'mailing:mailings_create' %}">Создайте рассылку</a>
    </div>
    <p></p>
    {% if user.is_authenticated %}
    <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество рассылок - {{ count_mailings }}
            <a class="btn btn-outline-primary me-md-2" href="{% url 'mailing:mailings' %}">Перейти к рассылкам</a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество активных рассылок - {{ active_mailings }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество получателей - {{ recipients_count }}
            <a class="btn btn-outline-primary me-md-2" href="{% url 'recipient:recipients' %}">Перейти к получателям</a>
        </li>
    </ul>
    {% endif %}
    <p></p>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for blog in blogs %}
        <div class="col">
            <div class="card shadow-sm h-100">
                <img src="/media/{{ blog.image }}" class="img-thumbnail" alt="...">
                <div class="card-body">
                    <p class="card-text">{{ blog.title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a class="btn btn-outline-primary me-md-2" href="{% url 'blog:blogs_detail' blog.pk %}">Читать</a>
                        </div>
                        <small class="text-body-secondary">{{ blog.publication_date }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}