blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    # Просмотр деталей блога
    # cache_page(60) - кэширует результаты выполнения представления на 60 секунд
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blogs_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('mailings/', include('mailing.urls', namespace='mailing')),
    path('mailing_logs/', include('mailing_logs.urls', namespace='mailing_log')),
    path('recipients/', include('recipient.urls', namespace='recipient')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # Список рассылок
    path('', MailingListView.as_view(), name='mailings'),

    # Детали рассылки
    path('<int:pk>/', MailingDetailView.as_view(), name='mailings_detail'),

    # Создание новой рассылки
    path('create/', MailingCreateView.as_view(), name='mailings_create'),

    # Обновление рассылки
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailings_update'),

    # Удаление рассылки
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailings_delete'),

    # Изменение статуса рассылки
    path('change_status/<int:pk>/', change_mailing_status, name='change_status'),
]

main_page/urls.py
from django.urls import path

from main_page.apps import MainPageConfig
from main_page.views import main_page

app_name = MainPageConfig.name

urlpatterns = [
    path('', main_page, name='main_page'),
]

recipient/urls.py
from django.urls import path
from recipient.apps import RecipientConfig
from recipient.views import *

# Получаем имя приложения "recipient" из его конфигурации
app_name = RecipientConfig.name

urlpatterns = [
    # Маршрут для отображения списка получателей
    path('', RecipientListView.as_view(), name='recipients'),

    # Маршрут для отображения деталей конкретного получателя
    path('<int:pk>/', RecipientDetailView.as_view(), name='recipients_detail'),

    # Маршрут для создания нового получателя
    path('create/', RecipientCreateView.as_view(), name='recipients_create'),

    # Маршрут для редактирования существующего получателя
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='recipients_update'),

    # Маршрут для удаления существующего получателя
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='recipients_delete'),
]

mailing/models.py
from django.db import models
from django.urls import reverse

from recipient.models import Recipient
from users.models import User

# Определение пустых значений, которые можно использовать в опциях моделей
NULLABLE = {'blank': True, 'null': True}


class Mailing(models.Model):
    # Определение констант для выбора периодичности рассылки
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    # Определение констант для статусов рассылки
    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    # Определение полей модели
    title = models.CharField(max_length=250, verbose_name='название рассылки')
    email_subject = models.CharField(max_length=250, verbose_name='тема письма')
    email_body = models.TextField(verbose_name='содержание письма')
    mailing_time = models.DateTimeField(verbose_name='время рассылки')
    periodicity = models.CharField(max_length=20, choices=PERIODS, verbose_name='периодичность')
    status = models.CharField(max_length=20, choices=STATUSES, default=STATUS_CREATED, verbose_name='статус рассылки')

    recipient = models.ManyToManyField(Recipient, verbose_name='получатель', related_name='mailing')

    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='отправитель рассылки', **NULLABLE)

    def __str__(self):
        """
        Возвращает строковое представление объекта Mailing.
        """
        return self.title

    def get_absolute_url(self):
        """
        Возвращает абсолютный URL для просмотра этой рассылки.
        """
        return reverse('mailing', kwargs={'mailing_id': self.pk})

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'

main_page/models.py
from django.db import models

# Create your models here.

mailing/forms.py
from django import forms
from django.forms import DateTimeInput, CheckboxSelectMultiple
from mailing.models import Mailing
from recipient.models import Recipient


class MailingForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        """
        Инициализация формы для создания рассылки.

        Args:
            user (User): Пользователь, создающий рассылку.
            *args: Позиционные аргументы для передачи в конструктор родительской формы.
            **kwargs: Именованные аргументы для передачи в конструктор родительской формы.
        """
        super(MailingForm, self).__init__(*args, **kwargs)

        # Фильтрация получателей на основе пользователя
        if user:
            self.fields['recipient'].queryset = Recipient.objects.filter(sender=user)

    recipient = forms.ModelMultipleChoiceField(
        queryset=Recipient.objects.none(),  # Пустой queryset, он будет переопределен в __init__
        widget=CheckboxSelectMultiple,
        required=False,
        label='Получатели'
    )

    class Meta:
        model = Mailing
        fields = ('title', 'email_subject', 'email_body', 'mailing_time', 'periodicity', 'recipient')
        widgets = {
            'mailing_time': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

mailing/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from mailing.forms import MailingForm
from mailing.models import Mailing
from mailing.services import send_mailing_task


class MailingListView(PermissionRequiredMixin, ListView):
    """
    Представление для отображения списка рассылок.
    """
    model = Mailing
    permission_required = 'mailing.view_mailing'
    extra_context = {'title': 'Рассылки'}


class MailingDetailView(DetailView):
    """
    Представление для отображения рассылки.
    """
    model = Mailing
    extra_context = {'title': 'Рассылка'}


class MailingCreateView(LoginRequiredMixin, CreateView):
    """
    Представление для создания новой рассылки.
    """
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailings')
    extra_context = {'title': 'Создание рассылки'}

    def get_form_kwargs(self):
        """
        Получение аргументов для инициализации формы.
        В данном методе добавляем аргумент 'user' для формы, чтобы знать, какому пользователю принадлежит рассылка.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Устанавливаем 'user' равным текущему пользователю
        return kwargs

    def form_valid(self, form):
        """
        Обрабатывает данные формы при их валидности.
        Args:
            form (MailingForm): Форма для создания рассылки.
        Returns:
            HttpResponseRedirect: Перенаправляет на страницу со списком рассылок.
        """
        if form.is_valid():
            self.object = form.save(commit=False)  # Сохраняем объект, но не коммитим его пока
            self.object.sender = self.request.user

            # Проверяем, если время начала уже прошло, то отправляем рассылку сразу
            current_time = timezone.now()
            if self.object.mailing_time <= current_time:
                self.object.status = Mailing.STATUS_STARTED

            self.object.save()  # Теперь коммитим объект

            # Теперь добавляем связи с получателями
            form.save_m2m()

            # Если рассылку нужно запустить, то вызываем функцию для отправки
            if self.object.status == Mailing.STATUS_STARTED:
                send_mailing_task(self.object)

        return super().form_valid(form)


class MailingUpdateView(UpdateView):
    """
    Представление для редактирования рассылки.
    """
    model = Mailing
    form_class = MailingForm
    extra_context = {'title': 'Редактирование рассылки'}

    def get_form_kwargs(self):
        """
        Получение аргументов для инициализации формы.
        В данном методе добавляем аргумент 'user' для формы, чтобы знать, какому пользователю принадлежит рассылка.
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Устанавливаем 'user' равным текущему пользователю
        return kwargs

    def get_success_url(self):
        return reverse('mailing:mailings_detail', args=[self.kwargs.get('pk')])


class MailingDeleteView(DeleteView):
    """
    Представление для удаления рассылки.
    """
    model = Mailing
    success_url = reverse_lazy('mailing:mailings')
    extra_context = {'title': 'Удаление рассылки'}


def change_mailing_status(request, pk):
    # Получаем объект рассылки по идентификатору
    mailing = Mailing.objects.get(pk=pk)

    # Изменяем статус рассылки
    if mailing.status == 'done':
        mailing.status = 'started'
    elif mailing.status == 'started':
        mailing.status = 'done'

    # Сохраняем изменения
    mailing.save()

    # Перенаправляем пользователя на страницу, с которой он пришел
    return redirect('mailing:mailings')

main_page/views.py
from django.shortcuts import render

from mailing.models import Mailing
from main_page.services import get_blogs_cache
from recipient.models import Recipient


def main_page(request):
    """
    Отображает главную страницу.
    Args:
        request (HttpRequest): Запрос от пользователя.
    Returns:
        HttpResponse: Ответ, содержащий главную страницу.
    """
    blogs = get_blogs_cache()

    if request.user.is_authenticated:
        # Если пользователь аутентифицирован, получаем его рассылки и получателей
        mailings = Mailing.objects.filter(sender=request.user)
        active_mailings = len(Mailing.objects.filter(status=Mailing.STATUS_STARTED, sender=request.user))
        count_mailings = len(mailings)
        recipients_count = len(Recipient.objects.filter(sender=request.user))

        context = {
            'mailings': mailings,
            'active_mailings': active_mailings,
            'count_mailings': count_mailings,
            'blogs': blogs,
            'recipients_count': recipients_count,
            'title': 'Главная страница'
        }

    else:
        # Если пользователь не аутентифицирован, показываем только блоги
        context = {
            'blogs': blogs,
            'title': 'Главная страница'
        }

    return render(request, 'main_page/main_page.html', context=context)

templates/mailing/base.html
<!--{% load static %}-->
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
<!--    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_main_menu.html' %}
{% block content %}
{% endblock %}
{% include 'mailing/includes/inc_footer.html' %}
<!--<script src="{% static 'css/js/bootstrap.bundle.min.js' %}"></script>-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/mailing/mailing_confirm_delete.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="container">
   <div class="card-body">
        <form method="post" action="" class="form-floating">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Вы подтверждаете, что хотите удалить рассылку {{ object }}?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'mailing:mailings_detail' object.pk %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

templates/mailing/mailing_detail.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ object }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ object.email_subject }}</h5>
            <p class="card-text">{{ object.email_body }}</p>
            <p class="card-text">Получатели:
                {% for recipient in object.recipient.all %}
                {{ recipient }};
                {% endfor %}
            </p>
            <p class="card-text">Периодичность рассылки: {{ object.periodicity }}</p>
            <p class="card-text">Статус рассылки: {{ object.status }}</p>
            <a href="{% url 'mailing:mailings_update' object.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'mailing:mailings_delete' object.pk %}" class="btn btn-danger">Удалить</a>
        </div>
        <div class="card-footer text-muted">
            <div class="row text-center">
                <div class="col-4">Статус рассылки: {{ object.status }}</div>
                <div class="col-4">Периодичность рассылки: {{ object.periodicity }}</div>
                <div class="col-4">{{ object.mailing_time }}</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/mailing/mailing_form.html
{% extends 'main_page/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    {% if object %}
    <h1 class="display-4">Редактирование рассылки</h1>
    {% else %}
    <h1 class="display-4">Создание рассылки</h1>
    {% endif %}
</div>
<form method="post" class="form-floating" enctype="multipart/form-data">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    {% if object %}
                    <a href="{% url 'mailing:mailings_detail' object.pk %}" class="btn btn-warning">Отмена</a>
                    {% else %}
                    <a href="{% url 'mailing:mailings' %}" class="btn btn-warning">Отмена</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/mailing/mailing_list.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pb-md-4 mx-auto text-center">
    <h1 class="display-5">Рассылки</h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'mailing:mailings_create' %}">Создать рассылку</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'recipient:recipients' %}">Получатели</a>
    <a class="p-2 btn btn-outline-primary" href="{% url 'mailing_logs:mailing_logs' %}">Логи рассылки</a>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        {% if object.sender == request.user or perms.mailing.view_mailing %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">
                        {% if object.sender == request.user %}
                        <a href="{% url 'mailing:mailings_detail' object.pk %}">-> {{ object }} <-</a>
                        {% else %}
                        {{ object }}
                        {% endif %}
                    </h4>
                </div>
                <div class="card-body">
                    <h5 class="card-title pricing-card-title">{{ object.email_subject }}</h5>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li> {{ object.email_body|truncatechars:100 }}</li>
                        <li>Периодичность -
                            {% if object.periodicity == 'daily' %}
                            Ежедневно
                            {% elif object.periodicity == 'weekly' %}
                            Еженедельно
                            {% else %}
                            Ежемесячно
                            {% endif %}
                        </li>
                        <li>Статус рассылки -
                            {% if object.status == 'done' %}
                            Отключена
                            {% elif object.status == 'started' %}
                            Запущенна
                            {% elif object.status == 'created' %}
                            Создана
                            {% endif %}
                        </li>
                    </ul>
                </div>
                <div class="card-footer">
                        {% if object.status == 'done' %}
                        <a class="p-2 btn btn-outline-success" href="{% url 'mailing:change_status' object.pk %}">Запустить
                            рассылку</a>
                        {% elif object.status == 'started' %}
                        <a class="p-2 btn btn-outline-warning" href="{% url 'mailing:change_status' object.pk %}">Остановить
                            рассылку</a>
                        {% endif %}
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/mailing/main_page.html
{% extends 'mailing/base.html' %}

{% block content %}


<div class="container">
    <h1 class="display-4 text-center">Рассылки</h1>
    <ul class="list-group list-group-flush">
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество рассылок - {{ count_mailings }}
            <a class="btn btn-outline-primary me-md-2" href="{% url 'mailing:mailings' %}">Перейти к рассылкам</a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество активных рассылок -
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">Количество получателей - {{ recipients_count }}
            <a class="btn btn-outline-primary me-md-2" href="{% url 'recipient:recipients' %}">Перейти к получателям</a>
        </li>
    </ul>
    <p></p>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for blog in blogs %}
        <div class="col">
            <div class="card shadow-sm">
                <img src="/media/{{ blog.image }}" class="img-thumbnail" alt="...">
                <div class="card-body">
                    <p class="card-text">{{ blog.title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-body-secondary">{{ blog.publication_date }}</small>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}