blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import *

app_name = BlogConfig.name

urlpatterns = [
    # Просмотр деталей блога
    # cache_page(60) - кэширует результаты выполнения представления на 60 секунд
    path('<int:pk>/', cache_page(60)(BlogDetailView.as_view()), name='blogs_detail'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('mailings/', include('mailing.urls', namespace='mailing')),
    path('mailing_logs/', include('mailing_logs.urls', namespace='mailing_log')),
    path('recipients/', include('recipient.urls', namespace='recipient')),
    path('blogs/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import *

app_name = MailingConfig.name

urlpatterns = [
    # Список рассылок
    path('', MailingListView.as_view(), name='mailings'),

    # Детали рассылки
    path('<int:pk>/', MailingDetailView.as_view(), name='mailings_detail'),

    # Создание новой рассылки
    path('create/', MailingCreateView.as_view(), name='mailings_create'),

    # Обновление рассылки
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailings_update'),

    # Удаление рассылки
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailings_delete'),

    # Изменение статуса рассылки
    path('change_status/<int:pk>/', change_mailing_status, name='change_status'),
]

recipient/urls.py
from django.urls import path
from recipient.apps import RecipientConfig
from recipient.views import *

# Получаем имя приложения "recipient" из его конфигурации
app_name = RecipientConfig.name

urlpatterns = [
    # Маршрут для отображения списка получателей
    path('', RecipientListView.as_view(), name='recipients'),

    # Маршрут для отображения деталей конкретного получателя
    path('<int:pk>/', RecipientDetailView.as_view(), name='recipients_detail'),

    # Маршрут для создания нового получателя
    path('create/', RecipientCreateView.as_view(), name='recipients_create'),

    # Маршрут для редактирования существующего получателя
    path('update/<int:pk>/', RecipientUpdateView.as_view(), name='recipients_update'),

    # Маршрут для удаления существующего получателя
    path('delete/<int:pk>/', RecipientDeleteView.as_view(), name='recipients_delete'),
]

recipient/models.py
from django.db import models
from django.urls import reverse
from users.models import User

# Определение словаря NULLABLE для использования его в полях с опцией blank и null
NULLABLE = {'blank': True, 'null': True}


class Recipient(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='имя')  # Имя получателя
    middle_name = models.CharField(max_length=150, verbose_name='отчество', **NULLABLE)  # Отчество (необязательное)
    last_name = models.CharField(max_length=150, verbose_name='фамилия')  # Фамилия получателя
    email = models.EmailField(unique=True, verbose_name='контактный email')  # Уникальный email получателя
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)  # Комментарий к получателю (необязательный)

    # Связь с пользователем, который добавил данного получателя
    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='отправитель рассылки', **NULLABLE)

    # Метод для строкового представления объекта Recipient
    def __str__(self):
        return f'{self.email} ({self.last_name})'

    # Метод для получения абсолютного URL объекта Recipient
    def get_absolute_url(self):
        return reverse('recipient', kwargs={'recipient_id': self.pk})

    class Meta:
        verbose_name = 'получатель'  # Отображаемое имя модели в административной панели Django
        verbose_name_plural = 'получатели'  # Отображаемое имя во множественном числе

recipient/forms.py
from django import forms

from recipient.models import Recipient


class RecipientForm(forms.ModelForm):
    class Meta:
        model = Recipient
        fields = ('first_name', 'middle_name', 'last_name', 'email', 'comment')

recipient/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView

from recipient.forms import RecipientForm
from recipient.models import Recipient


class RecipientListView(ListView):
    """
    Представление для отображения списка получателей.
    """
    model = Recipient
    extra_context = {'title': 'Получатели'}


class RecipientDetailView(DetailView):
    """
    Представление для отображения деталей конкретного получателя.
    """
    model = Recipient
    extra_context = {'title': 'Получатель'}


class RecipientCreateView(LoginRequiredMixin, CreateView):
    """
    Представление для создания нового получателя.
    """
    model = Recipient
    form_class = RecipientForm
    success_url = reverse_lazy('recipient:recipients')
    extra_context = {'title': 'Добавление получателя'}

    def form_valid(self, form):
        """
        Обрабатывает данные формы при их валидности.
        """
        if form.is_valid():
            self.object = form.save()
            self.object.sender = self.request.user
            self.object.save()
        return super().form_valid(form)


class RecipientUpdateView(UpdateView):
    """
    Представление для редактирования существующего получателя.
    """
    model = Recipient
    form_class = RecipientForm
    extra_context = {'title': 'Редактирование получателя'}

    def get_success_url(self):
        return reverse('mailing:mailings_detail', args=[self.kwargs.get('pk')])


class RecipientDeleteView(DeleteView):
    """
    Представление для удаления существующего получателя.
    """
    model = Recipient
    success_url = reverse_lazy('recipient:recipients')
    extra_context = {'title': 'Удаление получателя'}

templates/recipient/recipient_confirm_delete.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="container">
   <div class="card-body">
        <form method="post" action="" class="form-floating">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Вы подтверждаете, что хотите удалить получателя {{ object }}?</p>
            <button type="submit" class="btn btn-danger">Удалить</button>
            <a href="{% url 'recipient:recipients' %}" class="btn btn-warning">Отмена</a>
        </form>
    </div>
</div>
{% endblock %}

templates/recipient/recipient_detail.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ object }}</h4>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ object.email_subject }}</h5>
            <p class="card-text">{{ object.email_body }}</p>
            <p class="card-text">Периодичность рассылки: {{ object.periodicity }}</p>
            <p class="card-text">Статус рассылки: {{ object.status }}</p>
            <a href="{% url 'mailing:mailings_update' object.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'mailing:mailings_delete' object.pk %}" class="btn btn-danger">Удалить</a>
        </div>
        <div class="card-footer text-muted">
            <div class="row text-center">
                <div class="col-4">Статус рассылки: {{ object.status }}</div>
                <div class="col-4">Периодичность рассылки: {{ object.periodicity }}</div>
                <div class="col-4">{{ object.mailing_time }}</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/recipient/recipient_form.html
{% extends 'main_page/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% if object %}
<h1 class="display-5 text-center">Редактирование получателя</h1>
{% else %}
<h1 class="display-5 text-center">Добавление получателя</h1>
{% endif %}

<form method="post" class="form-floating" enctype="multipart/form-data">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                    <a href="{% url 'mailing:mailings' %}" class="btn btn-warning">Отмена</a>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

templates/recipient/recipient_list.html
{% extends 'main_page/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pb-md-4 mx-auto text-center">
    <h1 class="display-5">Получатели</h1>
    <a class="p-2 btn btn-outline-primary" href="{% url 'recipient:recipients_create' %}">Добавить получателя</a>
</div>

<div class="container">
    <ul class="list-group list-group-flush">
        {% for object in object_list %}
        {% if object.sender == request.user %}
        <li class="list-group-item d-flex justify-content-between align-items-center">{{ object }}
        <a class="btn btn-danger me-md-2" href="{% url 'recipient:recipients_delete' object.pk %}">Х</a>
        </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>
{% endblock %}